version: 2

jobs:
  python3.6:
    working_directory: ~/auger-cli
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - restore_cache:
          key: auger-cli-{{ arch }}-3.6-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - run:
          command: |
            sudo pip install pipenv
            pipenv install
      - save_cache:
          key: auger-cli-{{ arch }}-3.6-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.6/site-packages"
      # TODO: Fix flake8 issues
      # - run:
      #     command: |
      #       pipenv run python setup.py flake8
      - run:
          command: |
            pipenv run python setup.py test
      - store_artifacts:
          path: test-reports
          destination: tr1
  python3.7:
    working_directory: ~/auger-cli
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.7/site-packages
      - restore_cache:
          key: auger-cli-{{ arch }}-3.7-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - run:
          command: |
            sudo pip install pipenv
            pipenv install
      - save_cache:
          key: auger-cli-{{ arch }}-3.7-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.7/site-packages"
      # TODO: Fix flake8 issues
      # - run:
      #     command: |
      #       pipenv run python setup.py flake8
      - run:
          command: |
            pipenv run python setup.py test
      - store_artifacts:
          path: test-reports
          destination: tr1

workflows:
  version: 2
  build:
    jobs:
      - python3.6
      - python3.7
