version: 2
jobs:
  build:
    working_directory: ~/auger-cli
    docker:
      - image: circleci/python:3.6-stretch
    steps:
      - checkout
      - restore_cache:
          key: auger-cli-{{ arch }}-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            python setup.py test
      - save_cache:
          key: auger-cli-{{ arch }}-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          command: |
            . venv/bin/activate
            python setup.py test
      - store_artifacts:
          path: test-reports/
          destination: tr1
